services:
  api:
    image: php:8.2-fpm
    depends_on: 
      - db
    volumes:
      - ./api:/var/www/html
    ports: 
      - 9000:9000
    networks: 
      - app-network
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports: 
      - 3306:3306
    networks: 
      - app-network
    volumes:
      - ./.db:/var/lib/mysql

networks: 
  app-network:
    driver: bridge